### ISSUE TITLE
User can create an entry

### ISSUE THREAD

**Issue by hellohien** [hnguy96/travel-memories#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a travel memory entry

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

In a responsive form, the user can input a place that they have visited, the date, and some of their favorite moments during the trip.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Create a travel memory](https://user-images.githubusercontent.com/59902729/119908004-734bf980-bf06-11eb-96b2-6837df435a55.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to organize a table called `memories` with categories of `location`, `date`, and `favoriteMoments`
- [x] Update `data.sql` to insert the categories into `memories` table

### ☁️ Server

- [x] Update `server/index.js` to create a `POST` method from `api/memories` and send the response back to the client side
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for form
- [x] Create a component for title of form
- [x] Create a component to display form page 
- [x] Create a component to send a `POST` request to `/api/memories` using `fetch`

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by hnguy96** [comment]
![May-27-2021 16-41-58](https://user-images.githubusercontent.com/59902729/119909867-c627b000-bf0a-11eb-9e31-0575bea9dec4.gif)
![May-27-2021 16-42-04](https://user-images.githubusercontent.com/59902729/119909870-c758dd00-bf0a-11eb-80e5-945839ba5d60.gif)
