### ISSUE TITLE
User can view popup of location

### ISSUE THREAD

**Issue by hellohien** [hnguy96/travel-memories#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

A user can view popup of each marker location

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks on a marker on the map, they can view a popup with its location

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![View popup of location](https://user-images.githubusercontent.com/59902729/120901946-758f1180-c5f2-11eb-8da3-9a3cf7c287a3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
### ⚡ Client

- [x] Update map component to attach a popup to each marker to display its location

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
