### ISSUE TITLE
User can sign-up

### ISSUE THREAD

**Issue by hellohien** [hnguy96/travel-memories#15]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can register for an account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can create an account including their username and password. By creating an account, the user can create and save their travel memory entries.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![User can sign-up](https://user-images.githubusercontent.com/59902729/124812301-47199480-df18-11eb-975b-3012c6a099e4.png)
![User can sign-up (desktop)](https://user-images.githubusercontent.com/59902729/124812307-48e35800-df18-11eb-8c9b-1b253848c568.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to create a table called `users` with `userId`, `username`, and `password`
- [x] Update `data.sql` to create a Guest account

### ☁️ Server

- [x] Update `server/index.js` to accept `POST` requests that updates the `users` table with a new user
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to render a sign-up form allowing users to register

### 🧑‍⚕️ Clean Up

- [x] Make sure burger menu is hidden
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
