### ISSUE TITLE
User can sign-in

### ISSUE THREAD

**Issue by hellohien** [hnguy96/travel-memories#16]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign in

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can either sign in with their account or as a guest to use the app

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![User can sign-in (desktop)](https://user-images.githubusercontent.com/59902729/123336544-e1321380-d4fa-11eb-85fc-50df64d58a1e.png)
![User can sign-in](https://user-images.githubusercontent.com/59902729/123335680-ad0a2300-d4f9-11eb-9c3e-c2d6b83195ce.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle `POST` requests to `api/users`
- [x] Check credentials, query database, and create token to send back to client.
- [x] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to render a form allowing users to log in
- [x] Update menu to have a Sign Out link

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
