### ISSUE TITLE
User can view marked locations on map

### ISSUE THREAD

**Issue by hellohien** [hnguy96/travel-memories#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view marked locations on the map based on where they've traveled to

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once the user creates a new entry, they can view a map of all the place they've visited based on their inputs.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![View marked locations on map](https://user-images.githubusercontent.com/59902729/120254387-92b49080-c23e-11eb-9d59-359b52140e4e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to have categories of `lat` and `long`

### ☁️ Server

- [x] Update `server/index.js` to have the `POST` method include `lat` and `long`
- [x] Update `server/index.js` to create a `GET` method to receive `lat` and `long` from `api/memories`
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update the component to send a POST request of `lat` and `long`
- [x] Create a component to send a GET request to `/api/memories` using fetch
- [x] Create a component to display a map
  - [x] Create new states of latitude and longitude
  - [x] Add a marker to the map each time the user submits an entry
  - [x] Add a control to zoom in and out of the map

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
