### ISSUE TITLE
User can view entries

### ISSUE THREAD

**Issue by hellohien** [hnguy96/travel-memories#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their travel memories

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Display the user's entries in reverse chronological order so they can see the newest ones first

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![View travel memories](https://user-images.githubusercontent.com/59902729/120397518-4e33fe00-c2ed-11eb-8004-b39e5c2b197d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component to display Travel Memory entries
- [x] Create a component to swap views between pages
- [x] Create a component to listen for `hashchange` events

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
