### ISSUE TITLE
User can search an entry by location

### ISSUE THREAD

**Issue by hellohien** [hnguy96/travel-memories#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search an entry by location name

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once the user's list gets too long, they can filter through it by using the search box to specify a location

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Search entry by location](https://user-images.githubusercontent.com/59902729/120555569-1c37a000-c3b0-11eb-9a83-215f9863715f.png)
![Search entry by location 2](https://user-images.githubusercontent.com/59902729/120555599-248fdb00-c3b0-11eb-878a-efb4ff3735d2.png)
![Search entry by location 3](https://user-images.githubusercontent.com/59902729/120555590-222d8100-c3b0-11eb-9677-53d714628fdc.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
### ⚡ Client

- [x] Create a component to display an `input` element to search a Travel Memory by location
  - [x] Assign the input value to a new state
  - [x] If a location includes the input value, display the location on the page

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
