### ISSUE TITLE
User can delete an entry

### ISSUE THREAD

**Issue by hellohien** [hnguy96/travel-memories#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete an entry

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can delete an entry from the same page as their entries.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Delete an entry](https://user-images.githubusercontent.com/59902729/120873791-74110b00-c558-11eb-8609-061744addc45.png) ![Delete an entry 2](https://user-images.githubusercontent.com/59902729/120873795-76736500-c558-11eb-9311-8fdaaa0d9d81.png) ![Delete an entry 3](https://user-images.githubusercontent.com/59902729/120873822-973bba80-c558-11eb-8bc4-ae5a280aca1a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to create a `DELETE` method from `api/memories/:memoryId` 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to send a `DELETE` request to `/api/memories/:memoryId` using `fetch` when the user selects a memory to delete
  - [x] Pass in selected `memoryId` to component to delete from database
- [x] Update component to display a delete icon for each memory
  - [x] When the user clicks the icon, show a confirmation modal
  - [x] If user clicks delete, delete memory from page and return back to page
  - [x] If user clicks cancel, return back to page

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
